name: integration-tests
on:
  workflow_dispatch:
    inputs:
      user_token:
        description: User token
        type: string
        required: true
      user_id:
        description: User id
        type: string
        default: c5418ed2-fd72-461c-944e-669a274cc201
jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: Integration tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run integration tests
        run: cargo test --features "integration-test"
        env:
          INTEGRATION_TEST_USER_ID: ${{github.event.inputs.user_id}}
          INTEGRATION_TEST_USER_TOKEN: ${{github.event.inputs.user_token}}
