name: integration-tests
on:
  push:
    branches:
      - andreypakhomov/zero-2890-run-cli-tests-in-github-actions-every-day
jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: Integration tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build the project with test feature flag
        run: cargo build --verbose --features mock-keyring

      - name: Run integration tests
        run: cargo test --no-build --verbose --features mock-keyring
        env:
          INTEGRATION_TEST_USER_ID: c5418ed2-fd72-461c-944e-669a274cc201
          INTEGRATION_TEST_USER_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoiYWNjZXNzVG9rZW4iLCJlbWFpbCI6ImNsaUB0ZXN0LmNvbSIsInJvbGUiOiJ1c2VyIiwidXNlcklkIjoiYzU0MThlZDItZmQ3Mi00NjFjLTk0NGUtNjY5YTI3NGNjMjAxIiwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiJjNTQxOGVkMi1mZDcyLTQ2MWMtOTQ0ZS02NjlhMjc0Y2MyMDEifSwiaWF0IjoxNzI3OTYxNDc4LCJleHAiOjE3Mjk5NDg2Mzk4NzYsImlzcyI6Inplcm8tYXBwIn0.yNbgNF-ZPa-qjfYZqLIGwzxQ9CDy_fwJted1wpqzyUI
