name: integration-tests
on:
  push:
    branches:
      - andreypakhomov/zero-2890-run-cli-tests-in-github-actions-every-day
jobs:
  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: Integration tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update stable && rustup default stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build project with feature flag
        run: cargo build --features mock-keyring

      - name: Run integration tests
        run: cargo test
